#Name of the workflow
name: "Deploy Terraform Infrastructure May7-2022"

#Condition for run
on:
  push:
    branches: [Main,May-6-2022]

# Jobs to run
jobs:
  TarraformPlan: # Job #1
    # Environment for Job #1
    name: "Plan Terraform Deployment"
    environment: "example"
    runs-on: ubuntu-latest
    continue-on-error: false
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
    defaults:
      run:
        working-directory: ./Terraform/May7-2022/
      

    # Steps to run
    steps:
      - name: "Checkout the repo"
        id: checkout_repo
        uses: actions/checkout@v2

      - name: Print Working folder
        id: PWD
        shell: pwsh
        run: pwd

      - name: Terraform Setup
        id: TFSetup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5

      - name: Check Terraform Format
        id: TFFormat
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: TFInit
        run: >
          terraform init
          -backend-config=subscription_id=${{ secrets.BACKEND_SUBSCRIPTION_ID }}
          -backend-config=tenant_id=${{ secrets.BACKEND_TENANT_ID }}
          -backend-config=resource_group_name=${{ secrets.BACKEND_RG_NAME }}
          -backend-config=storage_account_name=${{ secrets.BACKEND_SA_NAME }}
          -backend-config=container_name=${{ secrets.BACKEND_CONTAINER_NAME }}
          -backend-config=key=${{ secrets.BACKEND_KEY }}

      - name: Terraform Plan
        id: TFPlan
        run: terraform plan -var-file=caroline.tfvars
